services:
  app:
      build: .
      container_name: tl_connect_app
      ports:
        - "8080:8080"
      depends_on:
        - redis
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-d824dprtqb8s73c8ev5g-a.singapore-postgres.render.com/tl_connect
        SPRING_DATASOURCE_USERNAME: tl_connect_user
        SPRING_DATASOURCE_PASSWORD: NmPkL84Fx9l2ETf0L0Lh6wQJM3k3vOgD

        SPRING_DATA_REDIS_URL: redis://default:IEeZmI5yVe6Jpe0Ar3rmSKYomLamXr9E@redis-14192.c12.us-east-1-4.ec2.cloud.redislabs.com:14192

        MICROSOFT_TENANT_ID: aec003eb-c537-4e8a-b0f3-1144a93a60bc
        MICROSOFT_CLIENT_ID: 77df993d-e728-4b8e-9770-6b409aa99552
        MICROSOFT_CLIENT_SECRET: JhY8Q~WSogbcZXtKVx.UpRuWE8OxrX~efJfNCaUi

        JWT_SECRET: xBdqwDtJ6DuRJNtPLZESNWtvrWi4nBWwfT9Y8ma5PSj
        
        B2_AWS_ACCESS_KEY_ID: 005ae5cc2083fe60000000002
        B2_AWS_SECRET_ACCESS_KEY: K005fYW2dznJytAJBvPsA4NICbisFEM
        B2_END_POINT: https://s3.us-east-005.backblazeb2.com
        B2_BUCKET_NAME: student-application

        ZALOPAY_APP_ID: 2553
        ZALOPAY_KEY1: PcY4iZIKFCIdgZvA6ueMcMHHUbRLYjPL
        ZALOPAY_KEY2: kLtgPl8HHhfvMuDHPwKfgfsY4Ydm9eIz
        ZALOPAY_ENDPOINT_CREATE: https://sb-openapi.zalopay.vn/v2/create
        ZALOPAY_ENDPOINT_GET_STATUS: https://sb-openapi.zalopay.vn/v2/query
        ZALOPAY_ENDPOINT_PARTIAL_REFUND: https://sb-openapi.zalopay.vn/v2/refund
        ZALOPAY_ENDPOINT_QUERY_REFUND: https://sb-openapi.zalopay.vn/v2/query_refund
        ZALOPAY_REDIRECT_URL: http://localhost:5173/subscription-plan
        ZALOPAY_CALLBACK_URL: https://unplacatory-primogenital-maurice.ngrok-free.dev/api/v1/payments/callback

        CLOUDINARY_CLOUD_NAME: dm5ev1isi
        CLOUDINARY_API_KEY: 621295638567175
        CLOUDINARY_API_SECRET: IGjUNJE-gmlNb42o0hhCVXxDdmU

        VNPAY_TMN_CODE: GF62PGAD
        VNPAY_SECRET_KEY: 0NKP2HUQ85JUYJ1DRPSMJ2QOIOHIC7OR
        VNPAY_PAY_URL: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
        VNPAY_RETURN_URL: myapp://payment/result
        VNPAY_REFUND_URL: https://sandbox.vnpayment.vn/merchant_webapi/api/transaction
        VNPAY_COMMAND: pay
        VNPAY_API_URL: https://sandbox.vnpayment.vn/merchant_webapi/api/transaction
        VNPAY_VERSION: 2.1.0
        
        ATTENDANCE_SECRET: xBd36DtJ6D8RJNtPLZESNWtvrWi4hBWwfT9Y8ma5PSg
        ATTENDANCE_EXPIRATION: 15
        
  redis:
    image: redis:7.4.2
    ports:
      - "6379:6379"