spring:
    profiles:
        active: local
    servlet:
        multipart:
            max-file-size: 5MB
            max-request-size: 5MB
    application:
        name: TL_Connect
    datasource:
        url: jdbc:postgresql://localhost:5432/ThangLong
        username: postgres
        password: 123456
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        properties:
            hibernate:
                default_schema: public
        hibernate:
            ddl-auto: validate
        show-sql: true
microsoft:
    tenant-id: aec003eb-c537-4e8a-b0f3-1144a93a60bc
    client-id: 77df993d-e728-4b8e-9770-6b409aa99552

jwt:
  secret: xBdqwDtJ6DuRJNtPLZESNWtvrWi4nBWwfT9Y8ma5PSj

b2:
    aws_access_key_id: 005ae5cc2083fe60000000002
    aws_secret_access_key: K005fYW2dznJytAJBvPsA4NICbisFEM
    end_point: https://s3.us-east-005.backblazeb2.com
    bucket_name: student-application
chatbot:
    api-key: [ENCRYPTION_KEY]
    domain: http://127.0.0.1:8787