spring:
    datasource:
        url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
        driver-class-name: org.h2.Driver
        username: sa
        password:

    jpa:
        hibernate:
            ddl-auto: create-drop

    h2:
        console:
            enabled: true
    servlet:
        multipart:
            max-file-size: 5MB
            max-request-size: 5MB
    application:
        name: TL_Connect
    # datasource:
    #     url: jdbc:postgresql://localhost:5432/postgres
    #     username: postgres
    #     password: 123456
    # jpa:
    #     database-platform: org.hibernate.dialect.PostgreSQLDialect
    security:
        oauth2:
            client:
                provider:
                    azure:
                        issuer-uri: https://login.microsoftonline.com/aec003eb-c537-4e8a-b0f3-1144a93a60bc/v2.0
                        user-name-attribute: name
                registration:
                    azure-dev:
                        provider: azure
                        client-id: 77df993d-e728-4b8e-9770-6b409aa99552
                        client-secret: Ato8Q~g_FXr69xCkejOH2EZ2d4cIH1MxarOiGavX
                        scope:
                            - openid
                            - email
                            - profile

jwt:
  secret: xBdqwDtJ6DuRJNtPLZESNWtvrWi4nBWwfT9Y8ma5PSj

b2:
    aws_access_key_id: 4a6e05ecdce240a893cf0e16
    aws_secret_access_key: 005ae5cc2083fe60000000001
    end_point: https://s3.us-east-005.backblazeb2.com
    bucket_name: student-application