DROP TABLE IF EXISTS user_roles CASCADE;
DROP TABLE IF EXISTS student_contacts CASCADE;
DROP TABLE IF EXISTS emergency_contacts CASCADE;
DROP TABLE IF EXISTS identity_cards CASCADE;
DROP TABLE IF EXISTS health_insurances CASCADE;
DROP TABLE IF EXISTS academic_infos CASCADE;
DROP TABLE IF EXISTS student_classes CASCADE;
DROP TABLE IF EXISTS majors CASCADE;
DROP TABLE IF EXISTS student_majors CASCADE;
DROP TABLE IF EXISTS academic_advisors CASCADE;
DROP TABLE IF EXISTS faculties CASCADE;
DROP TABLE IF EXISTS departments CASCADE;
DROP TABLE IF EXISTS subjects CASCADE;
DROP TABLE IF EXISTS subject_prerequisites CASCADE;
DROP TABLE IF EXISTS study_programs CASCADE;
DROP TABLE IF EXISTS study_program_subjects CASCADE;
DROP TABLE IF EXISTS semesters CASCADE;
DROP TABLE IF EXISTS student_course_classes CASCADE;
DROP TABLE IF EXISTS student_semester_summaries CASCADE;
DROP TABLE IF EXISTS exam_schedules CASCADE;
DROP TABLE IF EXISTS student_exam_registrations CASCADE;
DROP TABLE IF EXISTS application_types CASCADE;
DROP TABLE IF EXISTS student_applications CASCADE;
DROP TABLE IF EXISTS application_attachments CASCADE;
DROP TABLE IF EXISTS class_schedules CASCADE;
DROP TABLE IF EXISTS course_classes CASCADE;
DROP TABLE IF EXISTS students CASCADE;
DROP TABLE IF EXISTS roles CASCADE;
DROP TABLE IF EXISTS oauth_users CASCADE;
DROP TABLE IF EXISTS notifications CASCADE;
DROP TABLE IF EXISTS lecturers CASCADE;
DROP TABLE IF EXISTS student_subject_results CASCADE;

CREATE TABLE oauth_users (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_uuid VARCHAR(255) UNIQUE NOT NULL,
  display_name VARCHAR(255),
  email VARCHAR(255) UNIQUE NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'BLOCKED')),
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now()
);

CREATE TABLE roles (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  code VARCHAR(50) UNIQUE NOT NULL,
  name VARCHAR(100),
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now()
);

CREATE TABLE user_roles (
  user_id BIGINT NOT NULL,
  role_id BIGINT NOT NULL,
  assigned_at TIMESTAMP DEFAULT now(),
  PRIMARY KEY (user_id, role_id),
  FOREIGN KEY (user_id) REFERENCES oauth_users(id) ON DELETE CASCADE,
  FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE
);

CREATE TABLE faculties (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  faculty_code VARCHAR(20) UNIQUE NOT NULL,
  faculty_name VARCHAR(255),
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now()
);

CREATE TABLE departments (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  faculty_id BIGINT NOT NULL,
  department_code VARCHAR(20) UNIQUE NOT NULL,
  department_name VARCHAR(255),
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now(),
  FOREIGN KEY (faculty_id) REFERENCES faculties(id)
);

CREATE TABLE majors (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  major_code VARCHAR(20) UNIQUE NOT NULL,
  major_name VARCHAR(100),
  faculty_id BIGINT NOT NULL,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now(),
  FOREIGN KEY (faculty_id) REFERENCES faculties(id)
);

CREATE TABLE student_classes (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  class_code VARCHAR(20) UNIQUE NOT NULL,
  major_id BIGINT NOT NULL,
  start_year INT,
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now(),
  FOREIGN KEY (major_id) REFERENCES majors(id)
);

CREATE TABLE lecturers (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  oauth_user_id BIGINT UNIQUE NOT NULL,
  department_id BIGINT,
  full_name VARCHAR(100),
  lecturer_code VARCHAR(20) UNIQUE NOT NULL,
  phone_number VARCHAR(20),
  email VARCHAR(255),
  status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'INACTIVE')),
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now(),
  FOREIGN KEY (oauth_user_id) REFERENCES oauth_users(id),
  FOREIGN KEY (department_id) REFERENCES departments(id)
);

CREATE TABLE students (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  oauth_user_id BIGINT UNIQUE NOT NULL,
  student_class_id BIGINT NOT NULL,
  full_name VARCHAR(255),
  student_code VARCHAR(20) UNIQUE NOT NULL,
  gender VARCHAR(20) NOT NULL DEFAULT 'NAM' CHECK (gender IN ('NAM', 'NU')),
  date_of_birth DATE,
  status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','SUSPENDED','GRADUATED','DROPPED_OUT','DELETED')),
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now(),
  FOREIGN KEY (oauth_user_id) REFERENCES oauth_users(id),
  FOREIGN KEY (student_class_id) REFERENCES student_classes(id)
);

CREATE TABLE academic_advisors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lecturer_id BIGINT NOT NULL,
  student_class_id BIGINT NOT NULL,
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now(),
  FOREIGN KEY (lecturer_id) REFERENCES lecturers(id),
  FOREIGN KEY (student_class_id) REFERENCES student_classes(id) ON DELETE CASCADE
);

CREATE TABLE student_contacts (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  student_id BIGINT UNIQUE NOT NULL,
  phone_number VARCHAR(20),
  address VARCHAR(255),
  email_personal VARCHAR(255),
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now(),

  FOREIGN KEY (student_id) REFERENCES students(id)
);

CREATE TABLE emergency_contacts (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  student_id BIGINT UNIQUE NOT NULL,
  full_name VARCHAR(100),
  phone_number VARCHAR(20),
  address VARCHAR(255),
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now(),
  FOREIGN KEY (student_id) REFERENCES students(id)
);

CREATE TABLE identity_cards (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT UNIQUE NOT NULL,
  card_number VARCHAR(20) UNIQUE NOT NULL,
  card_type VARCHAR(20) NOT NULL DEFAULT 'CCCD' CHECK (card_type IN ('CCCD','CMND')),
  issued_date DATE,
  issued_place VARCHAR(100),
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now(),
  FOREIGN KEY (student_id) REFERENCES students(id)
);

CREATE TABLE health_insurances (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT NOT NULL,
  insurance_number VARCHAR(20) UNIQUE,
  provider VARCHAR(100),
  valid_from DATE,
  valid_to DATE CHECK (valid_to >= valid_from),
  registered_hospital VARCHAR(255),
  status VARCHAR(20),
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now(),
  FOREIGN KEY (student_id) REFERENCES students(id)
);

CREATE TABLE academic_infos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT NOT NULL,
  cohort VARCHAR(20),
  position VARCHAR(50),
  education_mode VARCHAR(20) NOT NULL DEFAULT 'CHINH_QUY' CHECK (education_mode IN ('CHINH_QUY','LIEN_THONG')),
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now(),
  FOREIGN KEY (student_id) REFERENCES students(id)
);

CREATE TABLE study_programs (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  major_id BIGINT NOT NULL,
  study_program_code VARCHAR(20),
  study_program_name VARCHAR(255),
  total_credits INT,
  start_year INT NOT NULL,
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now(),

  FOREIGN KEY (major_id) REFERENCES majors(id)
);

CREATE TABLE student_majors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT NOT NULL,
  major_id BIGINT NOT NULL,
  study_program_id BIGINT NOT NULL,
  is_primary BOOLEAN,
  start_year INT,
  end_year INT,
  status VARCHAR(20) NOT NULL DEFAULT 'STUDYING' CHECK (status IN ('STUDYING', 'GRADUATED', 'DROPPED')),
  FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE,
  FOREIGN KEY (major_id) REFERENCES majors(id) ON DELETE CASCADE,
  FOREIGN KEY (study_program_id) REFERENCES study_programs(id)
);

CREATE TABLE subjects (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  faculty_id BIGINT,
  department_id BIGINT,
  subject_code VARCHAR(20) UNIQUE NOT NULL,
  subject_name VARCHAR(255) NOT NULL,
  credits INT NOT NULL,
  lecture_hours INT,
  practice_hours INT,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now(),
  FOREIGN KEY (faculty_id) REFERENCES faculties(id),
  FOREIGN KEY (department_id) REFERENCES departments(id)
);

CREATE TABLE subject_prerequisites (
  subject_id BIGINT NOT NULL,
  prerequisite_subject_id BIGINT NOT NULL,
  created_at TIMESTAMP DEFAULT now(),
  PRIMARY KEY (subject_id, prerequisite_subject_id),
  FOREIGN KEY (subject_id) REFERENCES subjects(id) ON DELETE CASCADE,
  FOREIGN KEY (prerequisite_subject_id) REFERENCES subjects(id) ON DELETE CASCADE
);

CREATE TABLE semesters (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  semester_name VARCHAR(50),
  start_date DATE,
  end_date DATE,
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now()
);

CREATE TABLE study_program_subjects (
  study_program_id BIGINT NOT NULL,
  subject_id BIGINT NOT NULL,
  semester_id BIGINT NOT NULL,

  elective_group VARCHAR(50),
  is_required BOOLEAN,

  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now(),

  PRIMARY KEY (study_program_id, subject_id),

  FOREIGN KEY (study_program_id) REFERENCES study_programs(id) ON DELETE CASCADE,
  FOREIGN KEY (subject_id) REFERENCES subjects(id) ON DELETE CASCADE,
  FOREIGN KEY (semester_id) REFERENCES semesters(id)
);

CREATE TABLE course_classes (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  lecturer_id BIGINT,
  subject_id BIGINT NOT NULL,
  semester_id BIGINT NOT NULL,
  class_code VARCHAR(20),
  class_name VARCHAR(100),
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now(),
  FOREIGN KEY (lecturer_id) REFERENCES lecturers(id),
  FOREIGN KEY (subject_id) REFERENCES subjects(id),
  FOREIGN KEY (semester_id) REFERENCES semesters(id)
);

CREATE TABLE student_course_classes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT NOT NULL,
  course_class_id BIGINT NOT NULL,
  created_at TIMESTAMP DEFAULT now(),
  UNIQUE (student_id, course_class_id),
  FOREIGN KEY (student_id) REFERENCES students(id),
  FOREIGN KEY (course_class_id) REFERENCES course_classes(id)
);

CREATE TABLE class_schedules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_class_id BIGINT NOT NULL,
  day_of_week INT NOT NULL CHECK (day_of_week BETWEEN 2 AND 8),
  start_period INT,
  end_period INT NOT NULL CHECK (end_period >= start_period),
  start_time TIME NOT NULL,
  end_time TIME NOT NULL CHECK (end_time > start_time),
  room varchar(50),
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now(),
  FOREIGN KEY (course_class_id) REFERENCES course_classes(id) ON DELETE CASCADE
);

CREATE TABLE student_subject_results (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  student_id BIGINT NOT NULL,
  subject_id BIGINT NOT NULL,
  semester_id BIGINT NOT NULL,
  credits INT NOT NULL,
  score_10 DECIMAL(4,2),
  score_4 DECIMAL(3,2),
  letter_grade VARCHAR(2),
  is_pass BOOLEAN,
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now(),
  FOREIGN KEY (student_id) REFERENCES students(id),
  FOREIGN KEY (subject_id) REFERENCES subjects(id),
  FOREIGN KEY (semester_id) REFERENCES semesters(id)
);

CREATE TABLE student_semester_summaries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT NOT NULL,
  study_program_id BIGINT NOT NULL,
  semester_id BIGINT NOT NULL,
  credits_registered INT,
  credits_passed INT,
  semester_gpa DECIMAL(4,2),
  conduct_score INT,
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now(),
  FOREIGN KEY (study_program_id) REFERENCES study_programs(id),
  FOREIGN KEY (student_id) REFERENCES students(id),
  FOREIGN KEY (semester_id) REFERENCES semesters(id)
);

CREATE TABLE exam_schedules (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  course_class_id BIGINT NOT NULL,
  semester_id BIGINT NOT NULL,
  exam_date DATE NOT NULL,
  start_time TIME NOT NULL,
  end_time TIME NOT NULL CHECK (end_time > start_time),
  exam_room VARCHAR(50),
  exam_location VARCHAR(100),
  exam_format VARCHAR(50),
  exam_type VARCHAR(50),
  note VARCHAR(255),
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now(),
  FOREIGN KEY (course_class_id) REFERENCES course_classes(id),
  FOREIGN KEY (semester_id) REFERENCES semesters(id)
);

CREATE TABLE student_exam_registrations (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  student_id BIGINT NOT NULL,
  exam_schedule_id BIGINT NOT NULL,
  exam_attempt INT NOT NULL,
  attendance_status VARCHAR(20) NOT NULL DEFAULT 'UPCOMING' CHECK (attendance_status IN ('ATTENDED','ABSENT','UPCOMING')),
  exam_status VARCHAR(20) NOT NULL DEFAULT 'NOT_YET' CHECK (exam_status IN ('NOT_YET','DONE')),
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now(),
  
  UNIQUE (student_id, exam_schedule_id, exam_attempt),

  FOREIGN KEY (student_id) REFERENCES students(id),
  FOREIGN KEY (exam_schedule_id) REFERENCES exam_schedules(id)
);

CREATE TABLE application_types (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  code VARCHAR(100) UNIQUE NOT NULL,
  name VARCHAR(255),
  created_at TIMESTAMP DEFAULT now()
);

CREATE TABLE student_applications (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  student_id BIGINT NOT NULL,
  application_type_id BIGINT NOT NULL,
  content TEXT,
  status VARCHAR(20) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING','APPROVED','REJECTED')),
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now(),

  FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE,
  FOREIGN KEY (application_type_id) REFERENCES application_types(id)
);

CREATE TABLE application_attachments (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  application_id BIGINT NOT NULL,
  file_key VARCHAR(255),
  original_filename VARCHAR(255),
  file_size BIGINT,
  created_at TIMESTAMP DEFAULT now(),

  FOREIGN KEY (application_id) REFERENCES student_applications(id) ON DELETE CASCADE
);

CREATE TABLE notifications (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  content TEXT NOT NULL,
  sender VARCHAR(255),
  target_type VARCHAR(20) NOT NULL DEFAULT 'ALL' CHECK (target_type IN ('ALL','CLASS','STUDENT')),
  target_id BIGINT,
  dead_line TIMESTAMP,
  created_at TIMESTAMP DEFAULT now()
);



